services:
  kaisantantoudaijin:
    image: ghcr.io/coord-e/kaisantantoudaijin:latest
    depends_on:
      - redis
    environment:
      KAISANDAIJIN_REDIS_URI: redis://redis/
      KAISANDAIJIN_DISCORD_TOKEN: ${KAISANDAIJIN_DISCORD_TOKEN:?}
  redis:
    image: redis:7
    command: redis-server --save 60 1
    volumes:
      - redis-data:/data
volumes:
  redis-data:
